# Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,32,7])

In [3]:
myarr

array([ 3,  6, 32,  7])

In [4]:
myarr[0]

3

In [5]:
print(type(myarr))

<class 'numpy.ndarray'>


In [6]:
myarr[0,1]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
myarr=np.array([[3,89,98,8]],np.int64)

In [ ]:
myarr[0,1]

In [ ]:
myarr.shape

In [ ]:
myarr.dtype

In [ ]:
myarr[0,1]=45

In [ ]:
myarr

#**Array creation: Conversion from other Python Structures**#

In [ ]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [ ]:
listarray

In [ ]:
listarray.dtype

In [ ]:
listarray.shape

In [ ]:
listarray.size

In [ ]:
listarray[0,1]=9

In [ ]:
listarray

In [ ]:
np.array({34,23,23})

In [ ]:
zeros=np.zeros((2,5))

In [ ]:
zeros

In [ ]:
zeros.dtype

In [ ]:
rng=np.arange(15)

In [ ]:
rng

In [ ]:
lspace=np.linspace(1,5,12)
#linear spacing using this function

In [ ]:
lspace

In [ ]:
lspace=np.linspace(1,4,3)

In [ ]:
lspace

In [ ]:

emp=np.empty((4,6))

In [ ]:
emp

In [ ]:
emp_like=np.empty_like(lspace)

In [ ]:
emp_like

In [ ]:
ide=np.identity(45)

In [ ]:
ide

In [ ]:
ide.shape

In [ ]:
arr=np.arange(99)

In [ ]:
arr

In [ ]:
arr.reshape(3,33)

In [ ]:
arr.reshape(3,31)

In [ ]:
arr=arr.reshape(3,33)

In [ ]:
arr

In [ ]:
arr.ravel()

In [ ]:
arr.shape

In [ ]:
arr=arr.ravel()

In [ ]:
arr

In [ ]:
arr.shape

In [7]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [8]:
ar=np.array(x)

In [9]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [10]:
ar.sum(axis=0)
# Here it is taking sum vertically

array([12,  8,  9])

In [12]:
ar.sum(axis=1)
#It sum is taking horizontally

array([ 6, 15,  8])

In [13]:
ar.T
#Transpose=row into column and coulmn into row

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [14]:
ar.flat

In [15]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [17]:
ar.ndim

2

In [18]:
ar.size

9

In [19]:
ar.nbytes
#nbytes=>showing how much space they are ocuppying. It show only occupying space.

36

In [20]:
#1-d array
one=np.array([1,3,4,345,2])

In [21]:
one.argmax()
#it gives value of index which hold highest value.

3

In [22]:
one.argmin()
#it gives value of index which holds lowest value.

0

In [23]:
one.argsort()
#it shows the index of the element in the increasing order

array([0, 4, 1, 2, 3], dtype=int64)

In [24]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [25]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [26]:
ar.argmin()

8

In [27]:
ar.argmax()

6

In [28]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [29]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [30]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [31]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [32]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [33]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [34]:
ar.reshape(9,0)

ValueError: cannot reshape array of size 9 into shape (9,0)

In [35]:
ar.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [36]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [37]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [38]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [39]:
[324,34]+[34,546]

[324, 34, 34, 546]

In [40]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [43]:
ar/ar2

C:\Users\Arun raj\AppData\Local\Temp\ipykernel_11312\2166607628.py:1: RuntimeWarning: divide by zero encountered in divide
  ar/ar2
C:\Users\Arun raj\AppData\Local\Temp\ipykernel_11312\2166607628.py:1: RuntimeWarning: invalid value encountered in divide
  ar/ar2


array([[1.   , 1.   , 3.   ],
       [1.   ,   inf, 1.   ],
       [0.875, 1.   ,   nan]])

In [44]:
ar2/ar

C:\Users\Arun raj\AppData\Local\Temp\ipykernel_11312\3416719587.py:1: RuntimeWarning: invalid value encountered in divide
  ar2/ar


array([[1.        , 1.        , 0.33333333],
       [1.        , 0.        , 1.        ],
       [1.14285714, 1.        ,        nan]])

In [45]:
ar//ar

C:\Users\Arun raj\AppData\Local\Temp\ipykernel_11312\813699703.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  ar//ar


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 0]])

In [46]:
ar//ar2

C:\Users\Arun raj\AppData\Local\Temp\ipykernel_11312\216435550.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  ar//ar2


array([[1, 1, 3],
       [1, 0, 1],
       [0, 1, 0]])

In [47]:
ar**ar2

array([[      1,       4,       3],
       [    256,       1,   46656],
       [5764801,       1,       1]])

In [48]:
ar2-ar

array([[ 0,  0, -2],
       [ 0, -5,  0],
       [ 1,  0,  0]])

In [49]:
ar-ar2

array([[ 0,  0,  2],
       [ 0,  5,  0],
       [-1,  0,  0]])

In [50]:
np.sqrt(ar)
#squarerroot

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [51]:
ar.sum()

29

In [52]:
ar.max()

7

In [53]:
ar.min()

0

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [56]:
type(np.where(ar>5))

tuple

In [57]:
np.count_nonzero(ar)
#finding nonzero element into the array

8

In [58]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [59]:
ar[1,2]=0

In [60]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [69]:
import sys

In [70]:
py_ar =[0,4,55,2]

In [71]:
np_ar=np.array(py_ar)

In [72]:
sys.getsizeof(1)*len(py_ar)

112

In [73]:
np_ar.itemsize* np_ar.size

16

In [75]:
np_ar.tolist()

[0, 4, 55, 2]